### PR TITLE
MJD/JDE UTC fix + `to_time_scale` now available in Python

### LINKED ISSUE #257: from_gregorian but in GPST
Hello @ChristopherRabotin,

I would be interested in having an `Epoch` construction method similar  to `Epoch::from_gregorian_utc` but in `TimeScale::GPST`.

`from_gregorian_utc` is the best thing to use when all data fields are already known.

Such feature would solve the requirement I face in two of my parsers:

- in RINEX when parsing NAV ephemeris - the SV broadcasts Epoch expressed in their timescale (GPST for example)
- in SP3, all Epochs are expressed in a unique GNSS time scale

### LINKED ISSUE #302: (V4): from_mjd_utc / to_gregorian_utc reciprocal
Hello,

I think I picked up an issue when working with CGGTTS. 
In CGGTTS files, Epochs are expressed in MJD UTC. This is how I parse them:

image

`mjd` being an integer. 
I then use  `to_gregorian_utc`  in the mirror operation: 

image

In my example, I parsed and constructed mjd=59567 h=0 mins=14 seconds=0. 
Then, dumping generates mjd=59567 h=0 mins=14 seconds=37 (leap second issue ?)

### LINKED ISSUE #331: Python lib needs a function to change time scales
This is currently only possible in Rust, but it's quite useful in general, and Python needs to have access to it.

### PR DESCRIPTION
**Pull request by ChristopherRabotin**
Closes #331 
Closes #257 
Closes #302 

This also makes #229 much easier to get started on. My only hesitation with that ticket is that in Python, we use `init_from_unix_seconds` _a lot_ and we're launching in a few weeks so I'm hesitant to change my habits this close to launch.

### CODE REVIEW

File: src/epoch/mod.rs
Comment (ChristopherRabotin) [inline src/epoch/mod.rs:1]: Most of the changes here are for the initializers that were moved to `initializers.rs`.

File: src/epoch/initializers.rs [hunk 1]
```diff
@@ -0,0 +1,409 @@
...
+        );
+        Self {
+            duration: (days - MJD_J1900) * Unit::Day,
+            time_scale,
+        }
+    }
+
+    #[must_use]
+    pub fn from_mjd_utc(days: f64) -> Self {
+        Self::from_mjd_in_time_scale(days, TimeScale::UTC)
```
Comment (ChristopherRabotin) [inline src/epoch/initializers.rs:121]: This function previously called `from_mjd_tai` and then manually applied the leap seconds. Now it calls the `from_mjd_in_time_scale` function which correctly sets the time scale without changing the duration.

File: src/epoch/initializers.rs [hunk 2]
```diff
@@ -0,0 +1,409 @@
...
+        );
+        Self {
+            duration: (days - MJD_J1900 - MJD_OFFSET) * Unit::Day,
+            time_scale,
+        }
+    }
+
+    #[must_use]
+    pub fn from_jde_utc(days: f64) -> Self {
+        Self::from_jde_in_time_scale(days, TimeScale::UTC)
```
Comment (ChristopherRabotin) [inline src/epoch/initializers.rs:158]: The `from_jde_utc` function has the same bug as in #302 , so I've done the same fix.

File: tests/epoch.rs [hunk 3]
```diff
@@ -2069,11 +2069,17 @@ fn regression_test_gh_282() {
 fn regression_test_gh_288() {
     use core::str::FromStr;
     let epoch = Epoch::from_str("2021-03-06 11:14:40.9960 GPST").unwrap();
+    let epoch_from_gpst =
```
Comment (ChristopherRabotin) [inline tests/epoch.rs:2072]: Additional test for #257 .

File: tests/epoch.rs [hunk 4]
```diff
@@ -2137,3 +2143,32 @@ fn regression_test_gh_317() {
         nanos
     );
 }
+
+#[test]
+fn regression_test_gh_302() {
```
Comment (ChristopherRabotin) [inline tests/epoch.rs:2148]: New regression test for #302 .

File: tests/python/test_epoch.py [hunk 5]
```diff
@@ -25,6 +25,9 @@ def test_strtime():
         print(f"caught {e}")
     else:
         raise AssertionError("failed to catch parsing error")
+    
+    epoch_tdb = epoch.to_time_scale(TimeScale.TDB)
```
Comment (ChristopherRabotin) [inline tests/python/test_epoch.py:29]: Add a Python test for #331.
